---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: sharedlvm-csi-node
spec:
  selector:
    matchLabels:
      app: sharedlvm-csi-node
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sharedlvm-csi-node
    spec:
      hostNetwork: true
      containers:
        - name: csi-node-driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.6.3
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--csi-address=/csi/csi.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/sharedlvm.csi.leblanc.tech/csi.sock"
            - "--health-port=9809"
          ports:
            - containerPort: 9809
              name: healthz
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: sharedlvm-driver
          securityContext:
            privileged: true
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          args:
            - "--endpoint=/csi/csi.sock"
            - "--servertype=node"
            - "--nodeid=$(NODE_ID)"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: device-dir
              mountPath: /dev
            - name: etc-lvm
              mountPath: /etc/lvm
            - name: var-run-lvm
              mountPath: /var/run/lvm
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/
              # needed so that any mounts setup inside this container are
              # propagated back to the host machine.
              mountPropagation: "Bidirectional"
      volumes:
        - name: device-dir
          hostPath:
            path: /dev
            type: Directory
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: DirectoryOrCreate
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/sharedlvm.csi.leblanc.tech/
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet/
            type: Directory
        - name: etc-lvm
          hostPath:
            path: /etc/lvm
            type: Directory
        - name: var-run-lvm
          hostPath:
            path: /var/run/lvm
            type: Directory
