name: build

on:
  push:
    branches:
      - trunk
      - release-*
    tags:
      - v*
  pull_request:
    branches:
      - trunk
      - release-*

  workflow_dispatch:

jobs:
  build:
    name: Build sharedlvm Docker image
    runs-on: ubuntu-latest
    env:
      GOVER: 1.20
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/phillipleblanc/sharedlvm:latest
            ghcr.io/phillipleblanc/sharedlvm:0.1.0
            ghcr.io/phillipleblanc/sharedlvm:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
